"""frinds feature migration

Revision ID: 17733207e5f2
Revises: f5a6b7c8d9e0
Create Date: 2026-07-23 09:40:30.422287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17733207e5f2'
down_revision: Union[str, Sequence[str], None] = 'f5a6b7c8d9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_splits', sa.Column('friend_id', sa.UUID(), nullable=True))
    op.alter_column('expense_splits', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(op.f('fk_expense_splits_friend_id_friends'), 'expense_splits', 'friends', ['friend_id'], ['id'])
    op.add_column('friends', sa.Column('claimed_by_user_id', sa.UUID(), nullable=True))
    op.add_column('friends', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_friends_claimed_by_user_id_users'), 'friends', 'users', ['claimed_by_user_id'], ['id'])
    op.add_column('group_members', sa.Column('friend_id', sa.UUID(), nullable=True))
    op.alter_column('group_members', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(op.f('fk_group_members_friend_id_friends'), 'group_members', 'friends', ['friend_id'], ['id'])
    op.add_column('groups', sa.Column('is_shadow', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('settlements', sa.Column('payer_friend_id', sa.UUID(), nullable=True))
    op.add_column('settlements', sa.Column('receiver_friend_id', sa.UUID(), nullable=True))
    op.alter_column('settlements', 'payer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('settlements', 'receiver_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(op.f('fk_settlements_payer_friend_id_friends'), 'settlements', 'friends', ['payer_friend_id'], ['id'])
    op.create_foreign_key(op.f('fk_settlements_receiver_friend_id_friends'), 'settlements', 'friends', ['receiver_friend_id'], ['id'])
    
    ## check_cnstraint
    # expense_splits
    op.create_check_constraint(
        "ck_expense_splits_user_xor_friend",
        "expense_splits",
        "(user_id IS NOT NULL) <> (friend_id IS NOT NULL)",
    )
    
    # group_members
    op.create_check_constraint(
        "ck_group_members_user_xor_friend",
        "group_members",
        "(user_id IS NOT NULL) <> (friend_id IS NOT NULL)",
    )
    
    # settlements
    op.create_check_constraint(
        "ck_settlement_payer_xor",
        "settlements",
        "(payer_id IS NOT NULL) <> (payer_friend_id IS NOT NULL)",
    )

    op.create_check_constraint(
        "ck_settlement_receiver_xor",
        "settlements",
        "(receiver_id IS NOT NULL) <> (receiver_friend_id IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    ## check_constraint
    op.drop_constraint(
        "ck_settlement_receiver_xor",
        "settlements",
        type_="check",
    )

    op.drop_constraint(
        "ck_settlement_payer_xor",
        "settlements",
        type_="check",
    )

    op.drop_constraint(
        "ck_group_members_user_xor_friend",
        "group_members",
        type_="check",
    )

    op.drop_constraint(
        "ck_expense_splits_user_xor_friend",
        "expense_splits",
        type_="check",
    )
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_settlements_receiver_friend_id_friends'), 'settlements', type_='foreignkey')
    op.drop_constraint(op.f('fk_settlements_payer_friend_id_friends'), 'settlements', type_='foreignkey')
    op.alter_column('settlements', 'receiver_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('settlements', 'payer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('settlements', 'receiver_friend_id')
    op.drop_column('settlements', 'payer_friend_id')
    op.drop_column('groups', 'is_shadow')
    op.drop_constraint(op.f('fk_group_members_friend_id_friends'), 'group_members', type_='foreignkey')
    op.alter_column('group_members', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('group_members', 'friend_id')
    op.drop_constraint(op.f('fk_friends_claimed_by_user_id_users'), 'friends', type_='foreignkey')
    op.drop_column('friends', 'claimed_at')
    op.drop_column('friends', 'claimed_by_user_id')
    op.drop_constraint(op.f('fk_expense_splits_friend_id_friends'), 'expense_splits', type_='foreignkey')
    op.alter_column('expense_splits', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('expense_splits', 'friend_id')
    

    
    # ### end Alembic commands ###
