"""replace ghost with friend and created new model for friend

Revision ID: 39cd22944d16
Revises: af214072dfaa
Create Date: 2026-07-14 13:32:36.982275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39cd22944d16'
down_revision: Union[str, Sequence[str], None] = 'af214072dfaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('shadow_group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_friends_owner_id_users')),
    sa.ForeignKeyConstraint(['shadow_group_id'], ['groups.id'], name=op.f('fk_friends_shadow_group_id_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friends')),
    sa.UniqueConstraint('shadow_group_id', name=op.f('uq_friends_shadow_group_id'))
    )
    op.create_index(op.f('idx_friends_owner_id'), 'friends', ['owner_id'], unique=False)
    op.drop_constraint(op.f('password-reset-table_token_hash_key'), 'password-reset-table', type_='unique')
    op.create_unique_constraint(op.f('uq_password-reset-table_token_hash'), 'password-reset-table', ['token_hash'])
    op.drop_index(op.f('ix_users_user_code'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_google_id_key'), 'users', type_='unique')
    op.create_index(op.f('idx_users_user_code'), 'users', ['user_code'], unique=True)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.create_unique_constraint(op.f('uq_users_google_id'), 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_google_id'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_index(op.f('idx_users_user_code'), table_name='users')
    op.create_unique_constraint(op.f('users_google_id_key'), 'users', ['google_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_user_code'), 'users', ['user_code'], unique=True)
    op.drop_constraint(op.f('uq_password-reset-table_token_hash'), 'password-reset-table', type_='unique')
    op.create_unique_constraint(op.f('password-reset-table_token_hash_key'), 'password-reset-table', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('idx_friends_owner_id'), table_name='friends')
    op.drop_table('friends')
    # ### end Alembic commands ###
